version: "3.9"
services:
  postgres:
    container_name: ascii-rect-db
    image: postgres:14
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    # expose:
    #   - 5432
    environment:
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ascii_rect_dev

volumes:
  dbdata:
    name: ascii_rect-pg-data
